services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-global_exchange_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-global_exchange_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-global_exchange_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - SECRET_KEY=${SECRET_KEY:-tu_secret_key_aqui}
      - DEBUG=${DEBUG:-True}
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: