# Generated by Django 6.1 on 2026-08-31 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='keycloak_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único inmutable del usuario en Keycloak (claim sub).', max_length=255, null=True, unique=True, verbose_name='ID de Keycloak (sub)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta de usuario de Django asociada a esta ficha de cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(help_text='Dirección de correo electrónico única para notificaciones.', max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación.', verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_ruc',
            field=models.CharField(help_text='Número de documento de identidad fiscal o civil único.', max_length=20, unique=True, verbose_name='Documento / RUC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el cliente se encuentra actualmente activo en el sistema.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Nombre y apellido o razón social de la entidad cliente.', max_length=150, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segmentacion',
            field=models.CharField(choices=[('MIN', 'Minorista'), ('MAY', 'Mayorista'), ('COR', 'Corporativo'), ('VIP', 'VIP')], default='MIN', help_text='Categoría o segmento comercial asignado al cliente.', max_length=3, verbose_name='Segmentación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto (opcional).', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp automático de la última modificación.', verbose_name='Última Actualización'),
        ),
    ]
